### ISSUE TITLE
menu is not aligned well

### ISSUE THREAD

**Issue by 545zhou** [HalcyonChimera/cos.io#128]
There are so many elements in the menu that it's not aligned well. Need to decide what compromise to be done to make the menu realigned.

**Comment by atelic** [comment]
I've been playing around with this a lot today. One option is to remove the `container` div around the `navbar-collapse collapse` div which removes some of the padding and results in this:

![screen shot 2016-10-28 at 1 40 52 pm](https://cloud.githubusercontent.com/assets/8905795/19816194/56dca9de-9d14-11e6-889f-741df1680a1a.png)
