### ISSUE TITLE
issues on phone

### ISSUE THREAD

**Issue by 545zhou** [HalcyonChimera/cos.io#150]
Check the website cosio.herokuapp.com on a phone and see if there are display issues. Create tickets if issues found.

**Comment by atelic** [comment]
You can also emulate a bunch of different screen sizes by going to Chrome Dev Tools and clicking on the two phone looking icons next to the word "Elements"

**Comment by 545zhou** [comment]
That's convenient

**Comment by atelic** [comment]
For these issues, can you post what you see and what you expect to see? This will help others narrow down how to reproduce the problem.
