### ISSUE TITLE
table in phone view is not displayed right

### ISSUE THREAD

**Issue by 545zhou** [HalcyonChimera/cos.io#155]
tables should shrink.

**Comment by atelic** [comment]
I'm still seeing problems with the summary table on the TOP Guidelines page:
![screen shot 2016-11-07 at 12 05 40 pm](https://cloud.githubusercontent.com/assets/8905795/20067297/96e3b4fc-a4e2-11e6-84d4-70ff0fa54f93.png)

**Comment by 545zhou** [comment]
Hmm, I solved the journal tables but did not pay attention to this one. I'm going to solve it.

**Comment by atelic** [comment]
If you add the class `table-responsive` to the div around the table, it will make the table scroll horizontally on small devices like this:

![screen shot 2016-11-07 at 12 19 45 pm](https://cloud.githubusercontent.com/assets/8905795/20067775/81954bf4-a4e4-11e6-904c-05f0dc047499.png)

Not sure if that is what we want it to look like though

**Comment by 545zhou** [comment]
I think it works. How about you creating a pr about that?

**Comment by atelic** [comment]
Added in #162
