### ISSUE TITLE
Refactor models.py

### ISSUE THREAD

**Issue by atelic** [HalcyonChimera/cos.io#30]
The `models.py` file is quickly growing and could easily get out of hand.

It might be a good idea to refactor out some of the blocks to their own module. This way we can:
- Better organize the few models that will be left over
- Not have to place blocks in seemingly random places because the need to be declared before or after other ones. 
- Not slow down my editor on the giant file 😦

**Comment by NyanHelsing** [comment]
👍 👍 👍

**Comment by NyanHelsing** [comment]
I'd like to have a panels module too. Theres some stuff in common that should probably be in a different app, like wagtailadmin branding stuff should be in an overrides app or a branding app or something?

**Comment by atelic** [comment]
Closed by #47
