### ISSUE TITLE
Setting color on the footer isn't functional

### ISSUE THREAD

**Issue by NyanHelsing** [HalcyonChimera/cos.io#37]
It's marked as a required field but there's nothing in the template to do anything with it

**Comment by atelic** [comment]
Is this something that we _want_ to be functional? This comes from the two and three block column blocks which also don't implement the background in their template. Is this something to keep or scrap? 

If keep, we are going to need more than just three color options.

**Comment by NyanHelsing** [comment]
I think scrap;  we should come up with a more robust way of allowing changes to style? what do you think?

**Comment by atelic** [comment]
I think for now we can get rid of the field and look at implementing a hex color picker ([something like this](https://bgrins.github.io/spectrum/)) at some point.
