### ISSUE TITLE
Generic Column

### ISSUE THREAD

**Issue by NyanHelsing** [HalcyonChimera/cos.io#39]
Two column block and three column block could be combined and made to be more generic. It might make editing easier if each column were its own block, and we handled creating the row transparently in the template; 

If we add a small checkbox in the corner of each block (or in a block settings pane) that would add a clearfix class to the element, we wouldn't need a dedicated clearfix block. 

Though -- I hate clearfixes in general; can we make it use `overflow: hidden` to make the parent of a set of floats contain the floats? this way we would only have one edge case where the width of the columns doesn't add to 12, and if there were two sets of columns immediately next to each other. We can solve this be requiring contiguous columns widths add up to multiples of twelve.

**Comment by atelic** [comment]
Wait, @HalcyonChimera it looks like you did this in d5ed9b3b7e01f3eba27971688824d8fa6f826271. Can this be closed?

**Comment by NyanHelsing** [comment]
Yep this got finished up over the weekend.
