### ISSUE TITLE
google map and photo stream are not exactly the same as the official website

### ISSUE THREAD

**Issue by 545zhou** [HalcyonChimera/cos.io#62]
![screen shot 2016-10-07 at 2 06 03 pm](https://cloud.githubusercontent.com/assets/4791500/19200480/3b865b7c-8c97-11e6-84c2-669957f178fc.png)
You can click the google map on the official site and it gets to the large view. Clicking the photo stream will pop a window floating to show a larger one.

![screen shot 2016-10-07 at 2 05 34 pm](https://cloud.githubusercontent.com/assets/4791500/19200526/7f6d3dec-8c97-11e6-85b4-157a274d5e96.png)
In our site, clicking the google map does not happen anything. The photo stream displays duplicated pictures and clicking one photo it will show at the very beginning of the page.

**Comment by NyanHelsing** [comment]
Looks like a different script was used to create the map. I think the photo stream can be tweaked with just a bit of CSS?

**Comment by atelic** [comment]
Closed in #73
