### ISSUE TITLE
The up picture could not be found

### ISSUE THREAD

**Issue by 545zhou** [HalcyonChimera/cos.io#63]
![screen shot 2016-10-07 at 2 15 29 pm](https://cloud.githubusercontent.com/assets/4791500/19200739/99b651b0-8c98-11e6-9d80-30eed4b101cb.png)

**Comment by atelic** [comment]
That file seems to be in the right spot in the codebase:

https://github.com/HalcyonChimera/cos.io/blob/559c53efc9d504e13302c78b5280e3a661d0781b/static/img/up.png

It was added 14 hours ago and I'm not seeing the error you posted

**Comment by 545zhou** [comment]
You could not see this on heroku? I got this error on heroku.

**Comment by NyanHelsing** [comment]
This need to be looking for the file on amazon s3. wagtail can load js on a page and pass it an argument to an initializer. Can we do this to pass the path of the image we want to use for the up button? That way it's passed the static path and editors could change the picture if they really wanted to as well.
