### ISSUE TITLE
MFR

### ISSUE THREAD

**Issue by NyanHelsing** [HalcyonChimera/cos.io#79]
MFR has a drop in renderer, lets make a block that a user can just add a ling and the mfr will render that document.

**Comment by atelic** [comment]
I can't seem to find any docs on a drop-in renderer. Do you know where I could find out more about this?

**Comment by NyanHelsing** [comment]
https://github.com/CenterForOpenScience/discourse-osf-plugin/blob/master/assets/javascripts/discourse/connectors/topic-title/mfr-view.hbs

**Comment by NyanHelsing** [comment]
maybe this has some things in it

**Comment by atelic** [comment]
This seems like useful code but I've spent some time trying to figure that as well as [this](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/filepage/index.js#L47) out but can't make much progress.

It looks like the file you link is accessing some settings for (osf|mfr) domains [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/filepage/index.js#L47) but I haven't been able to find those settings or anything like them. Maybe I'm just not understanding what is going on there?
