### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by NyanHelsing** [HalcyonChimera/cos.io#80]
There is a need to provide a way to get feedback from users. There is a wagtail form editor, lets look at what that's like.

**Comment by atelic** [comment]
Looks like a lot of work was done on this in 3c6afd835 and I built on some more styling in 7406af4. What else is needed on this?

**Comment by atelic** [comment]
From what I can tell, this should be able to be closed after #98 is merged. 
- Admin flow is good
- Styling looks good and consistent within the site and with the cos.io site
- Ability to use outside form actions as in the cos.io site
- As mentioned on #98, it is also possible for us to write our own routes that accept different POST requests by using [something like this](https://github.com/rapidpro/rapidpro-community-portal/blob/6f90ecaed723325b11ab20437fbfb356f365a910/portal_pages/models.py#L726)
